# Generated by Django 3.1.3 on 2021-01-24 14:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_md', models.TextField()),
                ('content_html', models.TextField()),
                ('content', models.TextField()),
                ('abstract', models.TextField()),
                ('img_url', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2021, 1, 24, 14, 50, 4, 223846))),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.sort')),
            ],
        ),
    ]
