# Generated by Django 3.1.3 on 2021-01-24 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210124_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 24, 17, 3, 29, 588319)),
        ),
    ]
