# Generated by Django 3.1.3 on 2021-01-30 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210127_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 30, 16, 34, 54, 152822)),
        ),
    ]
